# Generated by Django 5.2.7 on 2025-10-26 17:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('perfil', models.CharField(max_length=100)),
                ('actor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to='accounts.actor')),
            ],
            options={
                'db_table': 'perfil',
            },
        ),
    ]
